# Generated by Django 6.1.1 on 2026-09-11 19:06

import django.db.models.deletion
import projects.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledDomain',
            fields=[
                ('domain_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain_index', models.PositiveIntegerField()),
                ('domain_name', models.URLField(max_length=255, validators=[projects.models.validate_onion_url])),
                ('crawl_timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawled_domains', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('page_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_url', models.URLField(max_length=500)),
                ('page_name', models.CharField(max_length=255)),
                ('page_text', models.TextField()),
                ('content_length', models.PositiveIntegerField()),
                ('crawl_timestamp', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='projects.crawleddomain')),
            ],
        ),
    ]
