# Generated by Django 6.1.1 on 2026-09-11 21:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_crawleddomain_pagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedFeature',
            fields=[
                ('feature_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_type', models.CharField(choices=[('username', 'Username'), ('email', 'Email'), ('ip', 'IP Address'), ('post', 'Post'), ('review', 'Review'), ('product', 'Product'), ('other', 'Other')], max_length=50)),
                ('feature_value', models.TextField()),
                ('context', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('extracted_timestamp', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_features', to='projects.crawleddomain')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_features', to='projects.pagecontent')),
            ],
        ),
    ]
